const perform = async (z, bundle) => {
  const response = await z.request({
    url: "https://api.apifreaks.com/v1.0/geolocation/timezone",
    params: { "ip": bundle.inputData["ip"], "tz": bundle.inputData["tz"], "location": bundle.inputData["location"], "lat": bundle.inputData["lat"], "long": bundle.inputData["long"], "lang": bundle.inputData["lang"], "iata_code": bundle.inputData["iata_code"], "icao_code": bundle.inputData["icao_code"], "lo_code": bundle.inputData["lo_code"] },
  });
  return response.data;
};

export default {
  key: "get_timezone",
  noun: "Timezone",
  display: {
    label: "Timezone Lookup",
    description: "Retrieve current time, date, and timezone-related information by specifying a timezone name, location address, location coordinates, IP address, or use the client IP address if no parameter is passed.",
  },
  operation: {
    inputFields: [
      {
        key: "ip",
        label: "Ip",
        type: 'string',
        required: false,
        helpText: "IPv4 or IPv6 address to extract timezone information.",
      },
      {
        key: "tz",
        label: "Tz",
        type: 'string',
        required: false,
        helpText: "Timezone name (e.g., \"Asia/Kolkata\") to retrieve information directly.",
      },
      {
        key: "location",
        label: "Location",
        type: 'string',
        required: false,
        helpText: "Location string (preferably city and country) to extract timezone.",
      },
      {
        key: "lat",
        label: "Lat",
        type: 'string',
        required: false,
        helpText: "Latitude for geolocation lookup.",
      },
      {
        key: "long",
        label: "Long",
        type: 'string',
        required: false,
        helpText: "Longitude for geolocation lookup.",
      },
      {
        key: "lang",
        label: "Lang",
        type: 'string',
        required: false,
        helpText: "Language code for response localization (default is \"en\").",
      },
      {
        key: "iata_code",
        label: "Iata Code",
        type: 'string',
        required: false,
        helpText: "3-letter IATA airport code (e.g., JFK).",
      },
      {
        key: "icao_code",
        label: "Icao Code",
        type: 'string',
        required: false,
        helpText: "4-letter ICAO airport code (e.g., KJFK).",
      },
      {
        key: "lo_code",
        label: "Lo Code",
        type: 'string',
        required: false,
        helpText: "5-letter UN/LO city code.",
      },
    ],
    perform,
    sample: {
      "ip": "8.8.8.8",
      "time_zone": {
        "name": "United States",
        "offset": 12.34,
        "offset_with_dst": 12.34,
        "date": "2025-08-18",
        "date_time": "2025-08-18T11:11:57.143Z",
        "date_time_txt": "example",
        "date_time_wti": "example",
        "date_time_ymd": "example",
        "date_time_unix": 12.34,
        "time_24": "example",
        "time_12": "example",
        "week": 123,
        "month": 123,
        "year": 123,
        "year_abbr": "example",
        "is_dst": true,
        "dst_savings": 12.34,
        "dst_exists": true,
        "dst_start.utc_time": "example",
        "dst_start.duration": "example",
        "dst_start.gap": true,
        "dst_start.date_time_after": "example",
        "dst_start.date_time_before": "example",
        "dst_start.overlap": true,
        "dst_end.utc_time": "example",
        "dst_end.duration": "example",
        "dst_end.gap": true,
        "dst_end.date_time_after": "example",
        "dst_end.date_time_before": "example",
        "dst_end.overlap": true
      },
      "location": {
        "location_string": "Lahore",
        "continent_code": "AS",
        "continent_name": "Asia",
        "country_code2": "PK",
        "country_code3": "PAK",
        "country_name": "Pakistan",
        "country_name_official": "Islamic Republic of Pakistan",
        "is_eu": false,
        "state_prov": "Punjab",
        "state_code": "PK-PB",
        "district": "Lahore",
        "city": "Lahore",
        "locality": "",
        "zipcode": "54000",
        "latitude": "31.56568",
        "longitude": "74.31418"
      },
      "airport_detail": {
        "type": "large_airport",
        "name": "London Heathrow Airport",
        "latitude": 51.4706,
        "longitude": -0.46194,
        "elevation_ft": 83,
        "continent_code": "EU",
        "country_code": "GB",
        "state_code": "GB-ENG",
        "city": "London",
        "iata_code": "LHR",
        "icao_code": "EGLL",
        "faa_code": ""
      },
      "lo_code_details": {
        "lo_code": "NLRTM",
        "city": "Rotterdam",
        "state_code": "ZH",
        "country_code": "NL",
        "country_name": "",
        "location_type": "Port, Rail Terminal, Road Terminal, Airport, Postal Exchange",
        "latitude": 51.91667,
        "longitude": 4.5
      }
    },
  },
};
