const perform = async (z, bundle) => {
  const response = await z.request({
    url: "https://api.apifreaks.com/v1.0/pdf/files",
  });
  return response.data;
};

export default {
  key: "get_pdf_files",
  noun: "PDF",
  display: {
    label: "Get list of PDF files",
    description: "This API retrieves a list of all PDF files uploaded and generated by a specific user. Please note that if the user is part of an organization, only the Organization Administrator can access this endpoint. Organization Members cannot access this endpoint.",
  },
  operation: {
    inputFields: [

    ],
    perform,
  },
};
