const perform = async (z, bundle) => {
  const response = await z.request({
    url: "https://api.apifreaks.com/v1.0/pdf/files",
  });
  return response.data;
};

export default {
  key: "get_pdf_files",
  noun: "PDF",
  display: {
    label: "Get List of PDF Files",
    description: "This API retrieves a list of all PDF files uploaded and generated by a specific user. Please note that if the user is part of an organization, only the Organization Administrator can access this endpoint. Organization Members cannot access this endpoint.",
  },
  operation: {
    inputFields: [

    ],
    perform,
    sample: {
      "fileId": "a1b2c3d4-0000-0000-0000-000000000000",
      "fileName": "document.pdf",
      "fileType": "pdf",
      "fileCreationTime": "2025-08-14T23:12:08.487Z",
      "fileDeletionTime": "2025-09-13"
    },
  },
};
