const perform = async (z, bundle) => {
  const response = await z.request({
    url: "https://api.apifreaks.com/v1.0/screenshot",
    params: { "output": bundle.inputData["output"], "file_type": bundle.inputData["file_type"], "url": bundle.inputData["url"], "width": bundle.inputData["width"], "height": bundle.inputData["height"], "full_page": bundle.inputData["full_page"], "fresh": bundle.inputData["fresh"], "no_cookie_banners": bundle.inputData["no_cookie_banners"], "enable_caching": bundle.inputData["enable_caching"], "block_ads": bundle.inputData["block_ads"], "block_chat_widgets": bundle.inputData["block_chat_widgets"], "extract_text": bundle.inputData["extract_text"], "extract_html": bundle.inputData["extract_html"], "destroy_screenshot": bundle.inputData["destroy_screenshot"], "lazy_load": bundle.inputData["lazy_load"], "retina": bundle.inputData["retina"], "dark_mode": bundle.inputData["dark_mode"], "block_tracking": bundle.inputData["block_tracking"], "enable_incognito": bundle.inputData["enable_incognito"], "omit_background": bundle.inputData["omit_background"], "thumbnail_width": bundle.inputData["thumbnail_width"], "adjust_top": bundle.inputData["adjust_top"], "wait_for_event": bundle.inputData["wait_for_event"], "grayscale": bundle.inputData["grayscale"], "delay": bundle.inputData["delay"], "timeout": bundle.inputData["timeout"], "ttl": bundle.inputData["ttl"], "clip[x]": bundle.inputData["clip[x]"], "clip[y]": bundle.inputData["clip[y]"], "clip[width]": bundle.inputData["clip[width]"], "clip[height]": bundle.inputData["clip[height]"], "css_url": bundle.inputData["css_url"], "css": bundle.inputData["css"], "js_url": bundle.inputData["js_url"], "js": bundle.inputData["js"], "block_js": bundle.inputData["block_js"], "block_stylesheets": bundle.inputData["block_stylesheets"], "block_images": bundle.inputData["block_images"], "block_media": bundle.inputData["block_media"], "block_font": bundle.inputData["block_font"], "block_text_track": bundle.inputData["block_text_track"], "block_xhr": bundle.inputData["block_xhr"], "block_fetch": bundle.inputData["block_fetch"], "block_event_source": bundle.inputData["block_event_source"], "block_web_socket": bundle.inputData["block_web_socket"], "block_manifest": bundle.inputData["block_manifest"], "block_specific_requests": bundle.inputData["block_specific_requests"], "blur_selector": bundle.inputData["blur_selector"], "remove_selector": bundle.inputData["remove_selector"], "result_file_name": bundle.inputData["result_file_name"], "scrolling_screenshot": bundle.inputData["scrolling_screenshot"], "scroll_speed": bundle.inputData["scroll_speed"], "scroll_back": bundle.inputData["scroll_back"], "start_immediately": bundle.inputData["start_immediately"], "multiple_scrolling": bundle.inputData["multiple_scrolling"], "sizes": bundle.inputData["sizes"], "duration": bundle.inputData["duration"], "fail_on_error": bundle.inputData["fail_on_error"], "longitude": bundle.inputData["longitude"], "latitude": bundle.inputData["latitude"], "proxy": bundle.inputData["proxy"], "headers": bundle.inputData["headers"], "cookies": bundle.inputData["cookies"], "scroll_to_element": bundle.inputData["scroll_to_element"], "selector": bundle.inputData["selector"], "selector_to_click": bundle.inputData["selector_to_click"], "click_recursion": bundle.inputData["click_recursion"], "user_agent": bundle.inputData["user_agent"], "accept_languages": bundle.inputData["accept_languages"], "scroll_delay": bundle.inputData["scroll_delay"], "custom_html": bundle.inputData["custom_html"], "image_quality": bundle.inputData["image_quality"], "extract_markdown": bundle.inputData["extract_markdown"], "get_image_urls": bundle.inputData["get_image_urls"] },
  });
  return response.data;
};

export default {
  key: "website_screenshot",
  noun: "Screenshot",
  display: {
    label: "Capture a Website Screenshot",
    description: "Capture full-page screenshots and videos of websites with advanced options like device simulation, custom code injection, cookie banner blocking, and scrollable content recording.\nSupports multiple output formats including JSON, image, GIF, MP4, and WebM.",
  },
  operation: {
    inputFields: [
      {
        key: "output",
        label: "Output",
        type: 'string',
        required: false,
        helpText: "Output format for screenshot results",
        choices: ["json", "image"],
      },
      {
        key: "file_type",
        label: "File Type",
        type: 'string',
        required: false,
        helpText: "File type for screenshot output",
        choices: ["PNG", "JPEG", "WEBP", "PDF", "mp4", "gif", "webm"],
      },
      {
        key: "url",
        label: "Url",
        type: 'string',
        required: true,
        helpText: "URLs to capture screenshots of",
      },
      {
        key: "width",
        label: "Width",
        type: 'string',
        required: false,
        helpText: "Browser viewport width in pixels",
      },
      {
        key: "height",
        label: "Height",
        type: 'string',
        required: false,
        helpText: "Browser viewport height in pixels",
      },
      {
        key: "full_page",
        label: "Full Page",
        type: 'string',
        required: false,
        helpText: "Capture a full-page screenshot",
      },
      {
        key: "fresh",
        label: "Fresh",
        type: 'string',
        required: false,
        helpText: "Bypass cache and take a fresh screenshot",
      },
      {
        key: "no_cookie_banners",
        label: "No Cookie Banners",
        type: 'string',
        required: false,
        helpText: "Remove cookie banners from the screenshot",
      },
      {
        key: "enable_caching",
        label: "Enable Caching",
        type: 'string',
        required: false,
        helpText: "Enable caching for repeated requests",
      },
      {
        key: "block_ads",
        label: "Block Ads",
        type: 'string',
        required: false,
        helpText: "Block advertisements on the page",
      },
      {
        key: "block_chat_widgets",
        label: "Block Chat Widgets",
        type: 'string',
        required: false,
        helpText: "Block chat widget scripts from loading",
      },
      {
        key: "extract_text",
        label: "Extract Text",
        type: 'string',
        required: false,
        helpText: "Extract visible text from the page",
      },
      {
        key: "extract_html",
        label: "Extract Html",
        type: 'string',
        required: false,
        helpText: "Extract HTML content of the page",
      },
      {
        key: "destroy_screenshot",
        label: "Destroy Screenshot",
        type: 'string',
        required: false,
        helpText: "Auto-destroy screenshot after fetch",
      },
      {
        key: "lazy_load",
        label: "Lazy Load",
        type: 'string',
        required: false,
        helpText: "Enable lazy-loading content before screenshot",
      },
      {
        key: "retina",
        label: "Retina",
        type: 'string',
        required: false,
        helpText: "Capture screenshot in high-DPI (Retina) mode",
      },
      {
        key: "dark_mode",
        label: "Dark Mode",
        type: 'string',
        required: false,
        helpText: "Render page in dark mode",
      },
      {
        key: "block_tracking",
        label: "Block Tracking",
        type: 'string',
        required: false,
        helpText: "Block common user-tracking scripts",
      },
      {
        key: "enable_incognito",
        label: "Enable Incognito",
        type: 'string',
        required: false,
        helpText: "Enable private/incognito mode for browser session",
      },
      {
        key: "omit_background",
        label: "Omit Background",
        type: 'string',
        required: false,
        helpText: "Omit background color (transparent background)",
      },
      {
        key: "thumbnail_width",
        label: "Thumbnail Width",
        type: 'string',
        required: false,
        helpText: "Thumbnail width in pixels",
      },
      {
        key: "adjust_top",
        label: "Adjust Top",
        type: 'string',
        required: false,
        helpText: "Adjust top in pixels",
      },
      {
        key: "wait_for_event",
        label: "Wait For Event",
        type: 'string',
        required: false,
        helpText: "Wait for a specific load event before capturing the screenshot.",
        choices: ["load", "domcontentloaded", "networkidle"],
      },
      {
        key: "grayscale",
        label: "Grayscale",
        type: 'string',
        required: false,
        helpText: "Range:0 to 100 for grayscale filter",
      },
      {
        key: "delay",
        label: "Delay",
        type: 'string',
        required: false,
        helpText: "How many milliseconds to wait before taking the screenshot",
      },
      {
        key: "timeout",
        label: "Timeout",
        type: 'string',
        required: false,
        helpText: "Maximum timeout in milliseconds. Defalut is `10,000`",
      },
      {
        key: "ttl",
        label: "Ttl",
        type: 'string',
        required: false,
        helpText: "Number of seconds the screenshot should be cached",
      },
      {
        key: "clip[x]",
        label: "Clip[X]",
        type: 'string',
        required: false,
        helpText: "X position of the clipping rectangle in pixels",
      },
      {
        key: "clip[y]",
        label: "Clip[Y]",
        type: 'string',
        required: false,
        helpText: "Y position of the clipping rectangle in pixels",
      },
      {
        key: "clip[width]",
        label: "Clip[Width]",
        type: 'string',
        required: false,
        helpText: "Width of the clipping rectangle in pixels",
      },
      {
        key: "clip[height]",
        label: "Clip[Height]",
        type: 'string',
        required: false,
        helpText: "Height of the clipping rectangle in pixels",
      },
      {
        key: "css_url",
        label: "Css Url",
        type: 'string',
        required: false,
        helpText: "URL to CSS file",
      },
      {
        key: "css",
        label: "Css",
        type: 'string',
        required: false,
        helpText: "Your custom CSS code",
      },
      {
        key: "js_url",
        label: "Js Url",
        type: 'string',
        required: false,
        helpText: "URL to JS file",
      },
      {
        key: "js",
        label: "Js",
        type: 'string',
        required: false,
        helpText: "Your JS code",
      },
      {
        key: "block_js",
        label: "Block Js",
        type: 'string',
        required: false,
        helpText: "Block Scripts",
      },
      {
        key: "block_stylesheets",
        label: "Block Stylesheets",
        type: 'string',
        required: false,
        helpText: "Prevent the page's CSS stylesheets from loading before the screenshot is captured.",
      },
      {
        key: "block_images",
        label: "Block Images",
        type: 'string',
        required: false,
        helpText: "Prevent images from loading before the screenshot is captured.",
      },
      {
        key: "block_media",
        label: "Block Media",
        type: 'string',
        required: false,
        helpText: "Prevent audio and video media from loading before the screenshot is captured.",
      },
      {
        key: "block_font",
        label: "Block Font",
        type: 'string',
        required: false,
        helpText: "Block Fonts",
      },
      {
        key: "block_text_track",
        label: "Block Text Track",
        type: 'string',
        required: false,
        helpText: "Block Text Tracks",
      },
      {
        key: "block_xhr",
        label: "Block Xhr",
        type: 'string',
        required: false,
        helpText: "Block XHR Requests",
      },
      {
        key: "block_fetch",
        label: "Block Fetch",
        type: 'string',
        required: false,
        helpText: "Block Fetch Requests",
      },
      {
        key: "block_event_source",
        label: "Block Event Source",
        type: 'string',
        required: false,
        helpText: "Block EventSource (server-sent events) connections while the page loads.",
      },
      {
        key: "block_web_socket",
        label: "Block Web Socket",
        type: 'string',
        required: false,
        helpText: "Block Web Sockets",
      },
      {
        key: "block_manifest",
        label: "Block Manifest",
        type: 'string',
        required: false,
        helpText: "Block the page's web app manifest from loading.",
      },
      {
        key: "block_specific_requests",
        label: "Block Specific Requests",
        type: 'string',
        required: false,
        helpText: "Comma- or newline-separated list of specific request URLs to block. Each comma or new line is treated as a separate entry. For example: example.com/ads or example.com/app.js",
      },
      {
        key: "blur_selector",
        label: "Blur Selector",
        type: 'string',
        required: false,
        helpText: "Comma-separated list of indexed CSS selectors to blur. Format: `index:<selector>`, e.g., `0:.banner,1:#ads`.",
      },
      {
        key: "remove_selector",
        label: "Remove Selector",
        type: 'string',
        required: false,
        helpText: "Comma-separated list of indexed CSS selectors to remove. Format: `index:<selector>`, e.g., `0:.banner,1:#ads`.",
      },
      {
        key: "result_file_name",
        label: "Result File Name",
        type: 'string',
        required: false,
        helpText: "Specify a meaningful & unique file name to easily identify the screenshot result. Avoid using spaces or special characters; use hyphens or underscores to separate words.",
      },
      {
        key: "scrolling_screenshot",
        label: "Scrolling Screenshot",
        type: 'string',
        required: false,
        helpText: "**`Scrolling Screenshot`**: Capture a long scrolling screenshot. When true, disable `fullPage` and `freshScreenshot`.",
      },
      {
        key: "scroll_speed",
        label: "Scroll Speed",
        type: 'string',
        required: false,
        helpText: "Speed of scrolling during the screenshot.",
        choices: ["normal", "fast", "slow"],
      },
      {
        key: "scroll_back",
        label: "Scroll Back",
        type: 'string',
        required: false,
        helpText: "If true, the scroll will reverse back to the top after reaching the bottom.",
      },
      {
        key: "start_immediately",
        label: "Start Immediately",
        type: 'string',
        required: false,
        helpText: "If true, the scrolling capture will start immediately upon page load.",
      },
      {
        key: "multiple_scrolling",
        label: "Multiple Scrolling",
        type: 'string',
        required: false,
        helpText: "If true, multiple scrolling screenshots will be taken at different viewport sizes.",
      },
      {
        key: "sizes",
        label: "Sizes",
        type: 'string',
        required: false,
        helpText: "Comma-separated list of viewport sizes in the format index:XXw:YYh. Example: sizes=0:120w:300h,1:240w:500h",
      },
      {
        key: "duration",
        label: "Duration",
        type: 'string',
        required: false,
        helpText: "Duration in seconds for the scrolling capture. Acceptable range: 0 to 60 seconds.",
      },
      {
        key: "fail_on_error",
        label: "Fail On Error",
        type: 'string',
        required: false,
        helpText: "If true, returns an error when the target page responds with 4xx or 5xx status.",
      },
      {
        key: "longitude",
        label: "Longitude",
        type: 'string',
        required: false,
        helpText: "Specify longitude for the browser Geolocation API.",
      },
      {
        key: "latitude",
        label: "Latitude",
        type: 'string',
        required: false,
        helpText: "Specify latitude for the browser Geolocation API.",
      },
      {
        key: "proxy",
        label: "Proxy",
        type: 'string',
        required: false,
        helpText: "Allows defining a proxy for the connection. Provide a JSON string with keys: server (include port number), username, and password.",
      },
      {
        key: "headers",
        label: "Headers",
        type: 'string',
        required: false,
        helpText: "Custom HTTP headers to include as key=value pairs. Use a semicolon to separate multiple headers (e.g., key1=value1;key2=value2).",
      },
      {
        key: "cookies",
        label: "Cookies",
        type: 'string',
        required: false,
        helpText: "Cookies to include in the request before rendering. Supports single or multiple cookies. Example: cookie=value; otherCookie=otherValue;",
      },
      {
        key: "scroll_to_element",
        label: "Scroll To Element",
        type: 'string',
        required: false,
        helpText: "Scrolls the page to bring the specified CSS selector into view before capture.",
      },
      {
        key: "selector",
        label: "Selector",
        type: 'string',
        required: false,
        helpText: "CSS selector to capture a specific element. Only that element is rendered.",
      },
      {
        key: "selector_to_click",
        label: "Selector To Click",
        type: 'string',
        required: false,
        helpText: "CSS selector for an element to click before capturing the screenshot.",
      },
      {
        key: "click_recursion",
        label: "Click Recursion",
        type: 'string',
        required: false,
        helpText: "Number of times to click the selector (when set via selector_to_click). Default: 1.",
      },
      {
        key: "user_agent",
        label: "User Agent",
        type: 'string',
        required: false,
        helpText: "Custom User-Agent string sent in the request headers.",
      },
      {
        key: "accept_languages",
        label: "Accept Languages",
        type: 'string',
        required: false,
        helpText: "Sets the accepted languages for the HTTP request. Sent as the Accept-Language header.",
      },
      {
        key: "scroll_delay",
        label: "Scroll Delay",
        type: 'string',
        required: false,
        helpText: "Delay in milliseconds between scroll steps when lazy_load is enabled.",
      },
      {
        key: "custom_html",
        label: "Custom Html",
        type: 'string',
        required: false,
        helpText: "Custom HTML to render instead of loading a URL. Overrides the url option.",
      },
      {
        key: "image_quality",
        label: "Image Quality",
        type: 'string',
        required: false,
        helpText: "Compression level for JPEG output (0\u2013100). Lower = smaller file, higher = better quality. Only applies to JPEG.",
      },
      {
        key: "extract_markdown",
        label: "Extract Markdown",
        type: 'string',
        required: false,
        helpText: "Extracts rendered page content as a structured .md (Markdown) file.",
      },
      {
        key: "get_image_urls",
        label: "Get Image Urls",
        type: 'string',
        required: false,
        helpText: "Extracts all image URLs from the rendered DOM and returns them in structured format.",
      },
    ],
    perform,
    sample: {
      "url": "https://api.apifreaks.com/v1.0/screenshot/result/9f3c2a.png",
      "file_name": "screenshot.png",
      "file_type": "PNG",
      "width": 1920,
      "height": 1080,
      "success": true
    },
  },
};
